### ISSUE TITLE
migrate content to docs.mesa3d.org?

### ISSUE THREAD

**Issue by kusma** [virgil3d/virgil3d.github.io#3]
We currently have docs for [Venus](https://docs.mesa3d.org/drivers/venus.html) in the upstream mesa docs. I think it would make sense to migrate this content to the mesa docs system in a similar way, and forward requests there instead.

Cc: @airlied

**Comment by kusma** [comment]
I submitted an MR for the mesa-side [here](https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/13836).

**Comment by airlied** [comment]
I'm fine with this, if someone tells me what to click and where.

**Comment by kusma** [comment]
This is done, closing!
